name: CI with nginx
# 동작 조건
on:
  push:
    branches: [ "master" ]

jobs:
  # 프로젝트 빌드
  build-docker-image:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      # 3. Docker 이미지 빌드
      - name: docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/community_service_frontend .
  
      # 4. DockerHub 로그인
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
      # 5. Docker Hub 이미지 푸시
      - name: docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/community_service_frontend
